Fixes
logzio/terraform-provider-logzio pull request #85
Opened 2021-08-15 13:40 UTC by mirii1994

- v1.5
    - Update client version(v1.8).
    - `sub_account`:
        - **Breaking changes:**
            - Deprecated attribute `utilization_settings`. Use `frequency_minutes` and `utilization_enabled` instead. 
        - Added attributes `flexible` and `reserved_daily_gb`.
        - Refactor tests.
        - Refactor code to use Terraform's retry.
    - `endpoint`:
        - **Breaking changes:**
            - Types naming.
        - New endpoints for OpsGenie, ServiceNow and Microsoft Teams.
        - Fix bug for `body_template` for `custom` type ([#70](https://github.com/logzio/terraform-provider-logzio/issues/70)).
        - Refactor tests.
        - Refactor code to use Terraform's retry.
    - `alerts_v2`:
        - Fix bug for `filter_must`,`filter_must_not` ([#82](https://github.com/logzio/terraform-provider-logzio/issues/82))
        - Refactor tests.
        - Refactor code to use Terraform's retry.
    - `drop_filter`:
        - Improve tests.

2021-08-23 20:04 UTC, Doron-Bargo requested changes
Amazing work 
Some cosmetics changes

2021-08-23 20:04 UTC, Doron-Bargo commented on docs/data-sources/endpoint.md
> +* [OpsGenie](https://docs.logz.io/api/#operation/createOpsGenie).
why some links are update while other create?
Should all of them be linked to create operation?

2021-08-23 20:04 UTC, Doron-Bargo commented on logzio/resource_subaccount.go
> +		UtilizationSettings: sub_accounts.AccountUtilizationSettingsCreateOrUpdate{
didnt we say that we not going to use UtilizationSettings?

2021-08-23 20:04 UTC, Doron-Bargo commented on logzio/common.go
>  package logzio
can you move it to be under utils?

2021-08-23 20:04 UTC, Doron-Bargo commented on logzio/parsers.go
>  import (
can you move it to be under utils?

2021-08-23 20:04 UTC, Doron-Bargo commented on logzio/validators.go
>  	"fmt"
can you move it to be under utils?

2021-08-25 07:28 UTC, mirii1994 commented on docs/data-sources/endpoint.md
> +* [OpsGenie](https://docs.logz.io/api/#operation/createOpsGenie).
Probably happened when my eyes were really tired. Should be create. Fixing.

2021-08-25 07:37 UTC, mirii1994 commented on logzio/resource_subaccount.go
> +		UtilizationSettings: sub_accounts.AccountUtilizationSettingsCreateOrUpdate{
In the API, `utilizationSettings` is an object that contains two fields: `frequencyMinutes`, `utilizationEnabled`.
I wanted to flatten and simplify the configuration for the user, so I deprecated `utilization_settings`, and instead the user just needs to use `frequency_minutes` and `utilization_enabled` (they already used those fields, but inside `utilization_settings`). Behind the scenes, in the code, I insert those values to UtilizationSettings.

2021-08-31 07:11 UTC, Doron-Bargo approved these changes
Amazing

2021-08-31 18:45 UTC, caphrim007 commented
i'm eagerly awaiting this release. awesome job @mirii1994

2021-09-28 08:17 UTC, akvamalin commented
Hey guys,
thanks for implementing missing connectors (in particular MS Teams Webhook). Is there any plan when to merge this PR?
Looking forward for the merge,
Best regards.

2021-09-29 08:10 UTC, merged